name: tests
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests with coverage gate
        run: pytest -q --cov=server --cov-report=term-missing --cov-fail-under=80
